/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.8.0
 *
 * Project: 'Cortex-A7.Debug+MCIMX7D7_A7' 
 * Target:  'Debug+MCIMX7D7_A7' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "iMX7D_A7.h"



#endif /* RTE_COMPONENTS_H */
