/*
 * UVISION generated file: DO NOT EDIT!
 * Generated by: uVision version 5.42.0.0
 *
 * Project: 'Blinky_M4' 
 * Target:  'CMSIS-RTOS Blinky' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "iMX7D_M4.h"

/* ARM::CMSIS:RTOS2:Keil RTX5&Source@5.9.0 */
#define RTE_CMSIS_RTOS2                 /* CMSIS-RTOS2 */
#define RTE_CMSIS_RTOS2_RTX5            /* CMSIS-RTOS2 Keil RTX5 */
#define RTE_CMSIS_RTOS2_RTX5_SOURCE     /* CMSIS-RTOS2 Keil RTX5 Source */
/* Keil::Compiler&ARM Compiler:I/O:STDERR&User@1.2.0 */
#define RTE_Compiler_IO_STDERR          /* Compiler I/O: STDERR */
#define RTE_Compiler_IO_STDERR_User     /* Compiler I/O: STDERR User */
/* Keil::Compiler&ARM Compiler:I/O:STDIN&User@1.2.0 */
#define RTE_Compiler_IO_STDIN           /* Compiler I/O: STDIN */
#define RTE_Compiler_IO_STDIN_User      /* Compiler I/O: STDIN User */
/* Keil::Compiler&ARM Compiler:I/O:STDOUT&User@1.2.0 */
#define RTE_Compiler_IO_STDOUT          /* Compiler I/O: STDOUT */
#define RTE_Compiler_IO_STDOUT_User     /* Compiler I/O: STDOUT User */
/* Keil::Compiler&ARM Compiler:I/O:TTY&User@1.2.0 */
#define RTE_Compiler_IO_TTY             /* Compiler I/O: TTY */
#define RTE_Compiler_IO_TTY_User        /* Compiler I/O: TTY User */


#endif /* RTE_COMPONENTS_H */
